from vkbottle import Keyboard, Callback, Text, KeyboardButtonColor

PREDMETS = (
    Keyboard(one_time=False, inline=False)
    .add(Callback('Русск. яз. (база)', payload={'cmd':'rusyas'}))
    .add(Callback('Русск. яз. (профиль)', payload={'cmd':'rusyas_p'}))
    .row()
    .add(Callback('Русск. лит.', payload={'cmd':'ruslit'}))
    .add(Callback('Бел. яз.', payload={'cmd':'belyas'}))
    .row()
    .add(Callback('Бел. лит.', payload={'cmd':'bellit'}))
    .add(Callback('Математ. (база)', payload={'cmd':'mat'}))
    .row()
    .add(Callback('Математ. (профиль)', payload={'cmd':'mat_p'}))
    .add(Callback('Биолог.', payload={'cmd':'bio'}))
    .row()
    .add(Callback('Всем. истор.', payload={'cmd':'vistor'}))
    .add(Callback('Истор. Бел.', payload={'cmd':'bistor'}))
    .row()
    .add(Callback('Обществ.', payload={'cmd':'obsch'}))
    .add(Callback('Информат.', payload={'cmd':'info'}))
    .row()
    .add(Callback('Астроном.', payload={'cmd':'astro'}))
    .add(Callback('Физ.', payload={'cmd':'phys'}))
    .row()
    .add(Callback('Хим.', payload={'cmd':'him'}))
    .add(Callback('Географ.', payload={'cmd':'geo'}))
    .row()
    .add(Callback('Франц. яз. (Тараникова)', payload={'cmd':'fra_t'}))
    .add(Callback('Франц. яз. (Дорошкова)', payload={'cmd':'fra_d'}))
    .row()
    .add(Callback('Франц. яз. ()', payload={'cmd':'fra_'}))
    .add(Callback('Нем. яз.', payload={'cmd':'nem'}))
    .get_json()
)